language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# commands to install dependencies
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install -qq gnuplot"
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
